# Generated by Django 2.0.5 on 2018-05-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0002_auto_20180531_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketnote',
            old_name='date_created',
            new_name='last_activity_date',
        ),
        migrations.RenameField(
            model_name='ticketnote',
            old_name='resource_id',
            new_name='note_type',
        ),
        migrations.RenameField(
            model_name='ticketnote',
            old_name='ticket',
            new_name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='ticketnote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticketnote',
            name='member',
        ),
        migrations.AddField(
            model_name='ticketnote',
            name='creator_resource_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.Resource'),
        ),
        migrations.AddField(
            model_name='ticketnote',
            name='publish',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketnote',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticketnote',
            name='description',
            field=models.TextField(blank=True, max_length=3200, null=True),
        ),
    ]
