# Generated by Django 2.1.11 on 2019-09-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0003_ticketstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketstatus',
            old_name='is_default',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='is_default_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='parent_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='sort_order',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
