# Generated by Django 2.0.5 on 2018-05-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0003_auto_20180529_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='scheduled_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
