# Generated by Django 2.0.5 on 2018-05-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0003_auto_20180531_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketnote',
            options={'verbose_name_plural': 'Notes'},
        ),
    ]
