# Generated by Django 2.1.11 on 2019-09-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0004_auto_20190904_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketstatus',
            options={'verbose_name': 'Ticket statuses'},
        ),
    ]
