# Generated by Django 2.0.5 on 2018-05-29 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0004_auto_20180529_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.Account'),
        ),
    ]
