# Generated by Django 2.0.5 on 2018-05-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0004_auto_20180531_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_resource_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_resource_role_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='creator_resource_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='due_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='hours_to_be_scheduled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_activity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
