# Generated by Django 2.0.5 on 2018-05-31 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0005_auto_20180531_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='agreement_id',
            new_name='opportunity_id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='closed_date_utc',
            new_name='resolution_plan_due_date',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='date_resolved_utc',
            new_name='resolution_plan_due_date_time',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='date_resplan_utc',
            new_name='resolved_date_time',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='date_responded_utc',
            new_name='resolved_due_date_time',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='approved',
            new_name='sla_been_met',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='parent_ticket_id',
            new_name='sla_id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='res_plan_mins',
            new_name='ticket_category',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='resolve_mins',
            new_name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='budget_hours',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='closed_flag',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer_updated',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='entered_date_utc',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='has_child_ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_in_sla',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='last_updated_utc',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='required_date_utc',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='respond_mins',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sub_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sub_type_item',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='ticket',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tickets', to='djautotask.Project'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution',
            field=models.TextField(blank=True, max_length=32000, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
