# Generated by Django 2.0.5 on 2018-05-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0006_auto_20180530_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('summary',), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
