# Generated by Django 2.0.5 on 2018-05-31 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0006_auto_20180531_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='account',
            new_name='account_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='board',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='project',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='team',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_resource_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.Resource'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_resource_role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.Role'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creator_resource_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.Resource'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
