# Generated by Django 2.0.5 on 2018-05-30 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0007_auto_20180530_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutotaskBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='TicketNote',
        ),
        migrations.AddField(
            model_name='ticket',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_tickets', to='djautotask.Account'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djautotask.AutotaskBoard'),
        ),
    ]
