# Generated by Django 2.0.5 on 2018-05-31 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0007_auto_20180531_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('title',), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_resource_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_resource_tickets', to='djautotask.Resource'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_resource_role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_tickets', to='djautotask.Role'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creator_resource_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_resource_tickets', to='djautotask.Resource'),
        ),
    ]
