# Generated by Django 2.1.11 on 2019-09-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0008_merge_20190920_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='value',
        ),
        migrations.RemoveField(
            model_name='ticketpriority',
            name='value',
        ),
    ]
