# Generated by Django 2.0.5 on 2018-05-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0008_auto_20180531_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='number',
            new_name='account_number',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.NullBooleanField(),
        ),
    ]
