# Generated by Django 2.0.5 on 2018-05-31 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0010_auto_20180531_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketPriority',
            new_name='TicketTimeEntry',
        ),
        migrations.DeleteModel(
            name='BoardStatus',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
