# Generated by Django 2.0.5 on 2018-05-31 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0011_auto_20180531_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(blank=True, null=True)),
                ('date_worked', models.DateTimeField(blank=True, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('hours_to_bill', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('last_modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('last_modified_user_id', models.IntegerField(blank=True, null=True)),
                ('non_billable', models.NullBooleanField()),
                ('show_on_invoice', models.BooleanField()),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('summary_notes', models.TextField(blank=True, max_length=8000, null=True)),
                ('time_entry_type', models.IntegerField(blank=True, null=True)),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='djautotask.Resource')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='djautotask.Role')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='djautotask.Ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='TicketTimeEntry',
        ),
    ]
