# Generated by Django 2.0.5 on 2018-05-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0012_auto_20180531_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='resource_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djautotask.Resource'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djautotask.Role'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djautotask.Ticket'),
        ),
    ]
