# Generated by Django 2.0.5 on 2018-05-31 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0013_auto_20180531_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsecondaryresource',
            name='resource_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djautotask.Resource'),
        ),
        migrations.AddField(
            model_name='ticketsecondaryresource',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djautotask.Role'),
        ),
        migrations.AddField(
            model_name='ticketsecondaryresource',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djautotask.Ticket'),
        ),
    ]
