# Generated by Django 2.0.5 on 2018-05-31 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0015_auto_20180531_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_resource_role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_tickets', to='djautotask.ResourceRole'),
        ),
        migrations.AlterField(
            model_name='ticketsecondaryresource',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djautotask.ResourceRole'),
        ),
        migrations.RenameModel(
            old_name='AutotaskBoard',
            new_name='Department',
        ),
        migrations.AddField(
            model_name='resourcerole',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djautotask.Department'),
        ),
        migrations.AddField(
            model_name='resourcerole',
            name='resource_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djautotask.Resource'),
        ),
        migrations.AddField(
            model_name='resourcerole',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djautotask.Role'),
        ),
    ]
