# Generated by Django 2.0.5 on 2018-06-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0019_auto_20180601_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_activity_resource_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.Resource'),
        ),
    ]
