# Generated by Django 2.1.11 on 2019-10-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0018_auto_20191029_1621'),
        ('djautotask', '0020_auto_20191030_0916'),
    ]

    operations = [
    ]
