# Generated by Django 2.1.14 on 2020-02-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0041_merge_20200204_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('hourly_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('role_type', models.PositiveIntegerField(blank=True, null=True)),
                ('system_role', models.BooleanField(default=False)),
            ],
        ),
    ]
