# Generated by Django 2.1.14 on 2020-03-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0053_timeentry_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.Contract'),
        ),
    ]
