# Generated by Django 2.1.11 on 2020-04-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0056_merge_20200327_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasknote',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticketnote',
            options={},
        ),
        migrations.AddField(
            model_name='tasknote',
            name='publish',
            field=models.CharField(blank=True, choices=[(1, 'All Autotask Users'), (2, 'Internal Project Team')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketnote',
            name='publish',
            field=models.CharField(blank=True, choices=[(1, 'All Autotask Users'), (2, 'Internal Project Team')], max_length=20, null=True),
        ),
    ]
