# Generated by Django 2.1.11 on 2020-04-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0057_auto_20200406_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknote',
            name='publish',
            field=models.CharField(blank=True, choices=[(1, 'All Autotask Users'), (2, 'Internal Users')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketnote',
            name='publish',
            field=models.CharField(blank=True, choices=[(1, 'All Autotask Users'), (2, 'Internal Users')], max_length=20, null=True),
        ),
    ]
