# Generated by Django 2.1.11 on 2020-05-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0063_accountphysicallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecall',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.AccountPhysicalLocation'),
        ),
    ]
