# Generated by Django 2.1.14 on 2020-05-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0064_auto_20200511_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='remaining_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
