# Generated by Django 2.1.14 on 2020-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0065_auto_20200512_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
