# Generated by Django 2.1.14 on 2020-05-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0066_auto_20200512_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='service_level_agreement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
