# Generated by Django 3.1.2 on 2020-12-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0086_auto_20201210_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='additional_address_information',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_address2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_address3',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='middle_initial',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='receives_email_notifications',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='zip_code',
        ),
    ]
