# Generated by Django 3.1.7 on 2021-12-28 14:43

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0099_auto_20211124_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('is_default_value', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('label',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskCategoryTracker',
            fields=[
            ],
            options={
                'db_table': 'djautotask_taskcategory',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djautotask.taskcategory',),
        ),
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.taskcategory'),
        ),
    ]
