# Generated by Django 4.0 on 2022-02-16 14:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0103_auto_20220106_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=False)),
                ('use_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.usetype')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='allocationcode',
            name='use_type',
        ),
        migrations.DeleteModel(
            name='AllocationCodeTracker',
        ),
        migrations.RemoveField(
            model_name='task',
            name='allocation_code',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='allocation_code',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='allocation_code',
        ),
        migrations.DeleteModel(
            name='AllocationCode',
        ),
        migrations.CreateModel(
            name='BillingCodeTracker',
            fields=[
            ],
            options={
                'db_table': 'djautotask_billingcode',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djautotask.billingcode',),
        ),
        migrations.AddField(
            model_name='task',
            name='billing_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.billingcode'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='billing_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.billingcode'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='billing_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.billingcode'),
        ),
    ]
