# Generated by Django 4.0.7 on 2022-08-08 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0104_rename_allocationcode_billingcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknote',
            name='created_by_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djautotask.contact'),
        ),
    ]
