# Generated by Django 4.2.16 on 2024-09-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0117_alter_tasknote_task_alter_ticketnote_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_exclusion_set_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
