# Generated by Django 4.2.16 on 2024-10-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0118_contract_contract_exclusion_set_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractExcludedWorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_exclusion_set_id', models.IntegerField(blank=True, null=True)),
                ('excluded_work_types', models.ManyToManyField(related_name='excluded_in_contracts', to='djautotask.billingcode')),
            ],
        ),
        migrations.CreateModel(
            name='ContractExcludedRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_exclusion_set_id', models.IntegerField(blank=True, null=True)),
                ('excluded_roles', models.ManyToManyField(related_name='excluded_in_contracts', to='djautotask.role')),
            ],
        ),
        migrations.CreateModel(
            name='ContractExcludedWorkTypeTracker',
            fields=[
            ],
            options={
                'db_table': 'djautotask_contract_excluded_worktype',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djautotask.contractexcludedworktype',),
        ),
        migrations.CreateModel(
            name='ContractExcludeRoleTracker',
            fields=[
            ],
            options={
                'db_table': 'djautotask_contract_excluded_role',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djautotask.contractexcludedrole',),
        ),
    ]
