# Generated by Django 4.2.16 on 2024-11-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0121_merge_0120_merge_20241101_1316_0120_resource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketnote',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
