# Generated by Django 4.2.16 on 2025-10-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0125_alter_project_account_alter_task_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution',
            field=models.TextField(blank=True, max_length=32000, null=True),
        ),
    ]
