# Generated by Django 4.2.16 on 2026-03-13 16:00

import django.contrib.postgres.indexes
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0126_ticket_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='UDFDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('record_type', models.CharField(choices=[('ticket', 'Ticket'), ('task', 'Task'), ('project', 'Project')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('udf_type', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=50)),
                ('is_list', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AddField(
            model_name='project',
            name='udf_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='udf_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ticket',
            name='udf_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['udf_data'], name='at_project_udf_data_gin'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['udf_data'], name='at_task_udf_data_gin'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['udf_data'], name='at_ticket_udf_data_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='udfdefinition',
            unique_together={('record_type', 'name')},
        ),
        migrations.CreateModel(
            name='UDFDefinitionTracker',
            fields=[
            ],
            options={
                'db_table': 'djautotask_udfdefinition',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djautotask.udfdefinition',),
        ),
    ]
