# Generated by Django 4.2.16 on 2026-03-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djautotask', '0127_udfdefinition_alter_task_options_project_udf_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udfdefinition',
            name='is_list',
        ),
    ]
